language: minimal
sudo: required
services:
  - docker

env:
  global:
    - REPOSITORY="${DOCKER_USERNAME}"
    - TOOLS_TO_BUILD=""
    - CHANNELS_TO_BUILD=""
    - PATH=$HOME/.local/bin:$PATH # awscli

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

jobs:
  allow_failures:
    - env:
        - TOOLS_TO_BUILD="clippy"
    - env:
        - TOOLS_TO_BUILD="miri"
  include:
    - stage: build compiler containers
      env:
        - CHANNELS_TO_BUILD="stable"
      script: "true"
    - env:
        - CHANNELS_TO_BUILD="beta"
      script: "true"
    - env:
        - CHANNELS_TO_BUILD="nightly"
      script: "true"

    - stage: build tools
      env:
        - TOOLS_TO_BUILD="rustfmt"
      script: "false"
    - env:
        - TOOLS_TO_BUILD="clippy"
      script: "true"
    - env:
        - TOOLS_TO_BUILD="miri"
      script: "false"

    - stage: compile code
      env:
        - BUILDING="backend"
      before_install: &prep_cache
       - >
         mkdir -p
         $HOME/cache/rust/cargo/{git,registry}
         $HOME/cache/rust/target
         $HOME/cache/node/node_modules
         $HOME/cache/node/yarn-cache
       - pip install --user awscli
      script: ./.travis/compile-backend.sh
      before_cache: &clean_cache
        # Ignore the permissions set from running inside the container
        - sudo chmod -R a+rw $HOME/cache
      after_success:
        - ./.travis/upload-compiled-artifacts.sh
      cache: &cache_build
        directories:
          - $HOME/cache
    - env:
      - BUILDING="frontend"
      before_install: *prep_cache
      script: ./.travis/compile-frontend.sh
      before_cache: *clean_cache
      after_success:
        - ./.travis/upload-compiled-artifacts.sh
      cache: *cache_build
